# Generated by Django 4.2.7 on 2025-07-15 10:50

from django.db import migrations, models
import qr_payment_plugin.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRPaymentLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('payment_id', models.BigIntegerField()),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('ABANDONED', 'Abandoned')], max_length=20)),
                ('screenshot_file', models.ImageField(upload_to='screenshot/', validators=[qr_payment_plugin.models.validate_file_size])),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendorQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('qr_code', models.ImageField(upload_to='qr_code/', validators=[qr_payment_plugin.models.validate_file_size])),
            ],
        ),
    ]
