# Generated by Django 5.2.4 on 2025-07-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_payment_plugin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorqrcode',
            old_name='qr_code',
            new_name='qr_code_file',
        ),
        migrations.AddField(
            model_name='qrpaymentlog',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
