# Generated by Django 5.2.4 on 2025-07-18 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr_payment_plugin', '0002_rename_qr_code_vendorqrcode_qr_code_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrpaymentlog',
            old_name='payment_id',
            new_name='order_id',
        ),
    ]
